### PR TITLE
Feat/xapiens to main

### PR DESCRIPTION
**Pull request by coy102**
- Change theme colors
- New feat (User quota)

### CODE REVIEW

**Comment by anuradhawick** [comment]
image

Could you look into this @coy102 ?

**Comment by anuradhawick** [comment]
@coy102 in a future fix - please make sure the 409 error does not appear but rather have a more useful message for the user.

**Comment by coy102** [comment]
@anuradhawick  Well noted

**Comment by coy102** [comment]
I need to investigate from the BE side, if data is not available, it always says 409 @anuradhawick

**Pull request merged**
