### PR TITLE
Xapiens to main

### PR DESCRIPTION
**Pull request by coy102**
- Added aws-service
- Updated env.example
- Implement get estimation cost on changes

image

ref #13

### CODE REVIEW

**Comment by XTIDfdenni** [comment]
Approved from my side Mas @coy102

**Comment by anuradhawick** [comment]
I see this has been merged, before we had a chance to chat. :blush: 

We'll have to revisit this on Monday when we are back to work. I am unsure as to why we need to use secret keys for pricing endpoint.

```typescript
pricingCredentials: {
    accessKeyId: 'XXXXX',
    secretAccessKey: 'XXXXX',
  },
```

Unless we have absolutely no other way to do this using IAM. Usually we try to restrict identity based access to S3, DynamoDB and Cognito only. Because rountripping via an API makes no sense for file uploads, identity tied table entries or updating identity details. 

@Yatish0833 just tagging you here so we can chat on Monday.

Cheers,
Anuradha

**Comment by coy102** [comment]
We need the secret key to get pricing plans using `aws-sdk`, CMIIW @XTIDfdenni . I tried without the key and I got this error.

image

Or, you can give me another way

**Comment by anuradhawick** [comment]
We might need to do this on backend. I will chat to team and let you know Monday.

**Comment by coy102** [comment]
Ah i see

**Pull request merged**
