### PR TITLE
Merged to hub01 from xapiens

### PR DESCRIPTION
**Pull request by XTIDfdenni**

### CODE REVIEW

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
Ran Plan for 0 projects:

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
Ran Plan for 0 projects:

**Comment by XTIDfdenni** [comment]
atlantis plan -p hub01-workflow

**Comment by devopsxti** [comment]
**Plan Error**
```
no project with name 'hub01-workflow' is defined in 'atlantis.yaml'
```

**Comment by XTIDfdenni** [comment]
atlantis plan -p gxc-consortium-hub02

**Comment by devopsxti** [comment]
**Plan Error**
```
no project with name 'gxc-consortium-hub02' is defined in 'atlantis.yaml'
```

**Comment by XTIDfdenni** [comment]
atlantis plan -p gxc-consortium-hub01

**Comment by devopsxti** [comment]
Ran Plan for dir: `.` workspace: `hub01`

**Plan Error**
<details><summary>Show Output</summary>

```
running 'sh -c' 'set -e
echo "Checking AWS identity..."
unset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
aws sts get-caller-identity --profile $AWS_PROFILE

echo "Initializing submodule sbeacon & svep ..."
git submodule update --init --recursive

echo "Initializing Terraform..."
terraform init
terraform workspace new staging || true
terraform workspace select staging
' in '/atlantis-data/repos/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/47/hub01': exit status 255: running "set -e\necho \"Checking AWS identity...\"\nunset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID\naws sts get-caller-identity --profile $AWS_PROFILE\n\necho \"Initializing submodule sbeacon & svep ...\"\ngit submodule update --init --recursive\n\necho \"Initializing Terraform...\"\nterraform init\nterraform workspace new staging || true\nterraform workspace select staging\n" in "/atlantis-data/repos/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/47/hub01": 
Checking AWS identity...

[Errno 13] Permission denied: '/.aws'


```
</details>

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
Ran Plan for 0 projects:

**Comment by XTIDfdenni** [comment]
atlantis plan -p gxc-consortium-hub02

**Comment by devopsxti** [comment]
**Plan Error**
```
no project with name 'gxc-consortium-hub02' is defined in 'atlantis.yaml'
```

**Comment by XTIDfdenni** [comment]
atlantis plan -p gxc-consortium-hub01

**Comment by devopsxti** [comment]
Ran Plan for dir: `.` workspace: `hub01`

**Plan Error**
<details><summary>Show Output</summary>

```
running 'sh -c' 'set -e
echo "Checking AWS identity..."
unset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
aws sts get-caller-identity --profile $AWS_PROFILE

echo "Initializing submodule sbeacon & svep ..."
git submodule update --init --recursive

echo "Initializing Terraform..."
terraform init
terraform workspace new staging || true
terraform workspace select staging
' in '/atlantis-data/repos/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/47/hub01': exit status 255: running "set -e\necho \"Checking AWS identity...\"\nunset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID\naws sts get-caller-identity --profile $AWS_PROFILE\n\necho \"Initializing submodule sbeacon & svep ...\"\ngit submodule update --init --recursive\n\necho \"Initializing Terraform...\"\nterraform init\nterraform workspace new staging || true\nterraform workspace select staging\n" in "/atlantis-data/repos/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/47/hub01": 
Checking AWS identity...

The config profile (GXC-TF-User-Executor-Hub01) could not be found


```
</details>

**Pull request closed without merging**
