### PR TITLE
Merge test to hub01 from feature

### PR DESCRIPTION
**Pull request by XTIDfdenni**

### CODE REVIEW

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by devopsxti** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
**Plan Error**
```
parsing atlantis.yaml: repo config not allowed to set 'workflow' key: server-side config needs 'allowed_overrides: [workflow]'
```

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
Atlantis commands can't be run on closed pull requests

**Comment by devopsxti** [comment]
```
Error parsing command: EOF found when expecting closing quote
```

**Pull request closed without merging**
