### PR TITLE
Added Makefile & README-Makefile to run makefile deployment

### PR DESCRIPTION
**Pull request by XTIDfdenni**

### CODE REVIEW

**Review by XTIDfdenni — COMMENTED** [review]
Added this to make simplify process
@anuradhawick @NickEdwards7502

**Comment by XTIDfdenni** [comment]
Update this PR
https://github.com/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/pull/28/commits/48aacab4d149c7fdefd693daf4ec7df8ac1b7bae

**Comment by XTIDfdenni** [comment]
Enhance features:
https://github.com/GSI-Xapiens-CSIRO/BGSI-GeneticAnalysisSupportPlatformIndonesia-GASPI/pull/28/commits/3741c5db739cbff04ddfc98655437ff204f03f66

Install: `nvm`, `pnpm`, `docker`, `docker-compose`
---
cc: @anuradhawick , @NickEdwards7502

**Comment by devopsxti** [comment]
atlantis plan

**Comment by devopsxti** [comment]
atlantis help

**Comment by XTIDfdenni** [comment]
atlantis help

**Comment by XTIDfdenni** [comment]
atlantis plan

**Comment by devopsxti** [comment]
atlantis plan

**Pull request merged**
